MACRO(PennMUSH_MKCMDS)
    file(WRITE build/cmds.h "/* AUTOGENERATED FILE. DO NOT EDIT! */
#ifndef CMDS_H
#define CMDS_H
#include \"command.h\"\n\n")

file(WRITE build/funs.h "/* AUTOGENERATED FILE. DO NOT EDIT! */
#ifndef FUNS_H
#define FUNS_H")

    file(GLOB files RELATIVE ${CMAKE_HOME_DIRECTORY} "src/*.c")

    foreach(file IN ITEMS ${files})
        FILE(READ ${file} contents)
        file(APPEND build/cmds.h "/*\t\t${file}\t\t*/\n\n")
        file(APPEND build/funs.h "/*\t\t${file}\t\t*/\n\n")
        MESSAGE(STATUS ${file})

        foreach(LINE IN LISTS contents)
            unset(cmdmatch)
            unset(funmatch)
            string(REGEX MATCH "[ ]*COMMAND\\(([A-Za-z0-9_]+)\\)" cmdmatch "${LINE}")
            string(REGEX MATCH "[ ]*FUNCTION\\(([A-Za-z0-9_]+)\\)" funmatch "${LINE}")

            if(cmdmatch)
                file(APPEND build/cmds.h "PROTO_${cmdmatch};\n\n")
            endif()
            if(funmatch)
            string(STRIP "${funmatch}" funmatch)
            string(REPLACE "FUNCTION" "FUNCTION_PROTO" funmatch "${funmatch}")
                file(APPEND build/funs.h "${funmatch};\n\n")
            endif()
        endforeach(LINE IN ${contents})
    endforeach(file IN ITEMS ${files})
    file(APPEND build/funs.h "#endif\n")
    file(APPEND build/cmds.h "#endif\n")
    message(STATUS "cmds.h: Rebuild Complete")
ENDMACRO(PennMUSH_MKCMDS)

MACRO(PennMUSH_MKSWITCHES)
    file(WRITE build/switches.h "/* AUTOGENERATED FILE. DO NOT EDIT! */
#ifndef SWITCHES_H
#define SWITCHES_H\n\n")

    FILE(STRINGS src/SWITCHES sw_contents)
    set(switch_count 1)

    foreach(SW_LINE IN ITEMS ${sw_contents})
        file(APPEND build/switches.h "#define SWITCH_${SW_LINE} ${switch_count}\n")
        MATH(EXPR switch_count "${switch_count}+1") 
    endforeach(SW_LINE IN sw_contents)

    file(APPEND build/switches.h "\n#endif\n")
endmacro(PennMUSH_MKSWITCHES)
